# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "《异乡客》文字版"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "《异乡客》艺术集"
  pageRef = "gallery"
  weight = 20

[[main]]
  name = "AI辅助心得"
  pageRef = "experience"
  weight = 30

[[main]]
  name = "关于作者"
  pageRef = "authors"
  weight = 40


[[main]]
  identifier = "Website"
  pre = "globe"
  url = "http://lordli.cn"
  weight = 100

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/1eez"
  weight = 200

[[main]]
  identifier = "Weibo"
  pre = "email"
  url = "https://weibo.com/cnpro"
  weight = 300

[[main]]
  identifier = "PDF"
  pre = "download"
  url = "https://outsider.lord.li/outsider-lordli.zip"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20